apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bot2 
  janus-idp.io/tekton: bot2
  backstage.io/kubernetes-id: bot2
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: bot2
resources: 
- application-dev.yaml