apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bot2-gitops
  description: This is GitOps manifest for bot2   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bot2
    janus-idp.io/tekton: bot2 
    backstage.io/kubernetes-id: bot2 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bot2
