---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: bot2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bot2 
  name: bot2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi