apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bot2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bot2 
  name: bot2
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: bot2 
